sudo: false # run in a docker container
language: perl
perl:
  - "5.30"
  - "5.28"
  - "5.26"
env:
  - TRAVIS_RUST_VERSION=stable
  - TRAVIS_RUST_VERSION=beta
  - TRAVIS_RUST_VERSION=nightly

before_install:
  - curl -sSf https://build.travis-ci.org/files/rustup-init.sh | sh -s -- --default-toolchain=$TRAVIS_RUST_VERSION -y
  - export PATH="$HOME/.cargo/bin:$PATH"
  - rustc --version
  - rustup --version
  - cargo --version
  - echo

script:
  - cargo t
  - (cd t && perl Makefile.PL && make test)
