[package]
name = "perl-xs-derive-macro"
version = "0.1.0"
authors = ["perl-xs Authors"]

[lib]
name = "perlxs_derive"
proc-macro = true

[dependencies]
syn = "0.11.11"
quote = "0.3.15"
perl-xs-derive-macro-support = { path = "../derive-macro-support" }